// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import DashboardWrapper from "@/app/dashboardWrapper"; 
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,

} from '@clerk/nextjs';
import { ReactNode } from 'react';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hardware inventory management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
            
          </SignedIn>
          <main>
            <DashboardWrapper>{children}</DashboardWrapper>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}